add_rules("mode.debug", "mode.release")
toolchain("aarch64-none-linux-gnu")
    set_kind("standalone")
    set_sdkdir("/home/debin/.software/toolchains/aarch64-none-linux-gnu/")
toolchain_end()

set_toolchains("aarch64-none-linux-gnu")
target("arm_tiny")
    set_kind("binary")
    add_files("src/*.c")
    add_files("asm/*.S")
    add_includedirs("include")
    set_toolset("cc", "aarch64-none-linux-gnu-gcc")
    set_toolset("ld", "aarch64-none-linux-gnu-ld")
    set_toolset("ldflags", "-T link.lds")
    set_toolset("ldflags", "-fno-builtin-printf")
    set_toolset("ldflags", "-mgeneral-regs-only")
    set_toolset("ldflags", "-fno-pie")
